spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8002/
          predicates:
            - Path=/clients/**
        - id: r2
          uri: http://localhost:8001/
          predicates:
            - Path=/voitures/**